name: "Hello World"
description: "Greet someone and record the time"
inputs:
  node:
    description: "Node.js version"
    required: false
    default: ""
outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "node16"
  main: "index.mjs"
